-- Complete PostgreSQL DDL — extracted from this backend's models
-- 58 tables, 33 enum types, 57 foreign keys (57 inline + 0 ALTER for cycles), 6 indexes.
-- Generated by scripts/extract_schema.py — regenerate after model changes.
-- Companion document: docs/DATABASE_SCHEMA.md

-- To reset the schema, uncomment and run this block:
-- DROP TABLE IF EXISTS timesheets CASCADE;
-- DROP TABLE IF EXISTS payments CASCADE;
-- DROP TABLE IF EXISTS contracts CASCADE;
-- DROP TABLE IF EXISTS ticket_replies CASCADE;
-- DROP TABLE IF EXISTS tasks CASCADE;
-- DROP TABLE IF EXISTS proposals CASCADE;
-- DROP TABLE IF EXISTS project_members CASCADE;
-- DROP TABLE IF EXISTS portfolios CASCADE;
-- DROP TABLE IF EXISTS meetings CASCADE;
-- DROP TABLE IF EXISTS invoices CASCADE;
-- DROP TABLE IF EXISTS gallery CASCADE;
-- DROP TABLE IF EXISTS case_studies CASCADE;
-- DROP TABLE IF EXISTS tickets CASCADE;
-- DROP TABLE IF EXISTS testimonials CASCADE;
-- DROP TABLE IF EXISTS projects CASCADE;
-- DROP TABLE IF EXISTS leads CASCADE;
-- DROP TABLE IF EXISTS client_reports CASCADE;
-- DROP TABLE IF EXISTS client_files CASCADE;
-- DROP TABLE IF EXISTS training_enrollments CASCADE;
-- DROP TABLE IF EXISTS performance_reviews CASCADE;
-- DROP TABLE IF EXISTS payslips CASCADE;
-- DROP TABLE IF EXISTS leaves CASCADE;
-- DROP TABLE IF EXISTS employee_documents CASCADE;
-- DROP TABLE IF EXISTS comments CASCADE;
-- DROP TABLE IF EXISTS clients CASCADE;
-- DROP TABLE IF EXISTS attendance CASCADE;
-- DROP TABLE IF EXISTS role_permissions CASCADE;
-- DROP TABLE IF EXISTS resources CASCADE;
-- DROP TABLE IF EXISTS reports CASCADE;
-- DROP TABLE IF EXISTS notifications CASCADE;
-- DROP TABLE IF EXISTS media CASCADE;
-- DROP TABLE IF EXISTS employees CASCADE;
-- DROP TABLE IF EXISTS courses CASCADE;
-- DROP TABLE IF EXISTS blogs CASCADE;
-- DROP TABLE IF EXISTS audit_logs CASCADE;
-- DROP TABLE IF EXISTS applications CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;
-- DROP TABLE IF EXISTS technologies CASCADE;
-- DROP TABLE IF EXISTS solutions CASCADE;
-- DROP TABLE IF EXISTS settings CASCADE;
-- DROP TABLE IF EXISTS services CASCADE;
-- DROP TABLE IF EXISTS seo_metadata CASCADE;
-- DROP TABLE IF EXISTS roles CASCADE;
-- DROP TABLE IF EXISTS products CASCADE;
-- DROP TABLE IF EXISTS permissions CASCADE;
-- DROP TABLE IF EXISTS partners CASCADE;
-- DROP TABLE IF EXISTS page_views CASCADE;
-- DROP TABLE IF EXISTS page_contents CASCADE;
-- DROP TABLE IF EXISTS newsletter_subscribers CASCADE;
-- DROP TABLE IF EXISTS industries CASCADE;
-- DROP TABLE IF EXISTS faqs CASCADE;
-- DROP TABLE IF EXISTS events CASCADE;
-- DROP TABLE IF EXISTS downloads CASCADE;
-- DROP TABLE IF EXISTS departments CASCADE;
-- DROP TABLE IF EXISTS contact_submissions CASCADE;
-- DROP TABLE IF EXISTS categories CASCADE;
-- DROP TABLE IF EXISTS careers CASCADE;
-- DROP TABLE IF EXISTS awards CASCADE;
-- DROP TYPE IF EXISTS application_status CASCADE;
-- DROP TYPE IF EXISTS attendance_status CASCADE;
-- DROP TYPE IF EXISTS blog_status CASCADE;
-- DROP TYPE IF EXISTS career_employment_type CASCADE;
-- DROP TYPE IF EXISTS career_status CASCADE;
-- DROP TYPE IF EXISTS category_type CASCADE;
-- DROP TYPE IF EXISTS comment_status CASCADE;
-- DROP TYPE IF EXISTS contact_status CASCADE;
-- DROP TYPE IF EXISTS contract_status CASCADE;
-- DROP TYPE IF EXISTS document_type CASCADE;
-- DROP TYPE IF EXISTS employee_status CASCADE;
-- DROP TYPE IF EXISTS employment_type CASCADE;
-- DROP TYPE IF EXISTS gallery_type CASCADE;
-- DROP TYPE IF EXISTS invoice_status CASCADE;
-- DROP TYPE IF EXISTS lead_source CASCADE;
-- DROP TYPE IF EXISTS lead_status CASCADE;
-- DROP TYPE IF EXISTS leave_status CASCADE;
-- DROP TYPE IF EXISTS leave_type CASCADE;
-- DROP TYPE IF EXISTS meeting_status CASCADE;
-- DROP TYPE IF EXISTS notification_type CASCADE;
-- DROP TYPE IF EXISTS partner_type CASCADE;
-- DROP TYPE IF EXISTS payment_method CASCADE;
-- DROP TYPE IF EXISTS payment_status CASCADE;
-- DROP TYPE IF EXISTS payslip_status CASCADE;
-- DROP TYPE IF EXISTS project_status CASCADE;
-- DROP TYPE IF EXISTS proposal_status CASCADE;
-- DROP TYPE IF EXISTS task_priority CASCADE;
-- DROP TYPE IF EXISTS task_status CASCADE;
-- DROP TYPE IF EXISTS technology_category CASCADE;
-- DROP TYPE IF EXISTS ticket_priority CASCADE;
-- DROP TYPE IF EXISTS ticket_status CASCADE;
-- DROP TYPE IF EXISTS timesheet_status CASCADE;
-- DROP TYPE IF EXISTS user_role CASCADE;

CREATE TYPE application_status AS ENUM ('applied', 'shortlisted', 'interview', 'offered', 'rejected', 'hired');

CREATE TYPE attendance_status AS ENUM ('present', 'absent', 'half_day', 'holiday', 'weekend');

CREATE TYPE blog_status AS ENUM ('draft', 'published', 'archived');

CREATE TYPE career_employment_type AS ENUM ('full_time', 'part_time', 'contract', 'internship');

CREATE TYPE career_status AS ENUM ('open', 'closed');

CREATE TYPE category_type AS ENUM ('blog', 'gallery', 'download', 'event');

CREATE TYPE comment_status AS ENUM ('pending', 'approved', 'spam');

CREATE TYPE contact_status AS ENUM ('new', 'in_progress', 'resolved', 'spam');

CREATE TYPE contract_status AS ENUM ('pending', 'signed', 'void');

CREATE TYPE document_type AS ENUM ('resume', 'id_proof', 'contract', 'certificate', 'other');

CREATE TYPE employee_status AS ENUM ('active', 'on_leave', 'terminated');

CREATE TYPE employment_type AS ENUM ('full_time', 'part_time', 'contract', 'intern');

CREATE TYPE gallery_type AS ENUM ('image', 'video');

CREATE TYPE invoice_status AS ENUM ('draft', 'sent', 'paid', 'overdue', 'cancelled');

CREATE TYPE lead_source AS ENUM ('website', 'contact_form', 'referral', 'campaign', 'cold_outreach', 'event', 'other');

CREATE TYPE lead_status AS ENUM ('new', 'contacted', 'requirement_gathering', 'proposal_sent', 'proposal_approved', 'converted', 'disqualified');

CREATE TYPE leave_status AS ENUM ('pending', 'approved', 'rejected', 'cancelled');

CREATE TYPE leave_type AS ENUM ('sick', 'casual', 'earned', 'unpaid', 'maternity', 'paternity');

CREATE TYPE meeting_status AS ENUM ('scheduled', 'completed', 'cancelled');

CREATE TYPE notification_type AS ENUM ('info', 'success', 'warning', 'error');

CREATE TYPE partner_type AS ENUM ('technology_partner', 'business_partner', 'reseller');

CREATE TYPE payment_method AS ENUM ('bank_transfer', 'card', 'upi', 'paypal', 'cheque', 'other');

CREATE TYPE payment_status AS ENUM ('pending', 'completed', 'failed', 'refunded');

CREATE TYPE payslip_status AS ENUM ('generated', 'paid');

CREATE TYPE project_status AS ENUM ('planning', 'in_progress', 'on_hold', 'completed', 'cancelled');

CREATE TYPE proposal_status AS ENUM ('draft', 'sent', 'viewed', 'accepted', 'rejected');

CREATE TYPE task_priority AS ENUM ('low', 'medium', 'high', 'urgent');

CREATE TYPE task_status AS ENUM ('todo', 'in_progress', 'in_review', 'done', 'blocked');

CREATE TYPE technology_category AS ENUM ('frontend', 'backend', 'database', 'cloud', 'devops', 'ai_ml', 'mobile', 'other');

CREATE TYPE ticket_priority AS ENUM ('low', 'medium', 'high', 'critical');

CREATE TYPE ticket_status AS ENUM ('open', 'in_progress', 'resolved', 'closed');

CREATE TYPE timesheet_status AS ENUM ('draft', 'submitted', 'approved', 'rejected');

CREATE TYPE user_role AS ENUM ('super_admin', 'admin', 'hr', 'sales', 'marketing', 'project_manager', 'developer', 'qa', 'support', 'finance', 'client', 'employee', 'guest');


CREATE TABLE awards (
	title VARCHAR(200) NOT NULL, 
	issued_by VARCHAR(200), 
	year INTEGER, 
	image VARCHAR(500), 
	description TEXT, 
	is_published BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);


CREATE TABLE careers (
	title VARCHAR(200) NOT NULL, 
	slug VARCHAR(220) NOT NULL, 
	department VARCHAR(100), 
	location VARCHAR(150), 
	employment_type career_employment_type NOT NULL, 
	experience_required VARCHAR(100), 
	description TEXT, 
	responsibilities VARCHAR[], 
	requirements VARCHAR[], 
	status career_status NOT NULL, 
	posted_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug), 
	UNIQUE (slug)
);


CREATE TABLE categories (
	name VARCHAR(150) NOT NULL, 
	slug VARCHAR(170) NOT NULL, 
	type category_type NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug), 
	UNIQUE (slug)
);


CREATE TABLE contact_submissions (
	name VARCHAR(150) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	phone VARCHAR(30), 
	company VARCHAR(200), 
	department VARCHAR(100), 
	subject VARCHAR(255), 
	message TEXT NOT NULL, 
	status contact_status NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);


CREATE TABLE departments (
	name VARCHAR(150) NOT NULL, 
	description TEXT, 
	head_employee_id UUID, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (name), 
	UNIQUE (name)
);


CREATE TABLE downloads (
	title VARCHAR(200) NOT NULL, 
	description TEXT, 
	file_url VARCHAR(500) NOT NULL, 
	file_type VARCHAR(20), 
	category VARCHAR(100), 
	download_count INTEGER NOT NULL, 
	requires_lead BOOLEAN NOT NULL, 
	is_published BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);


CREATE TABLE events (
	title VARCHAR(200) NOT NULL, 
	slug VARCHAR(220) NOT NULL, 
	description TEXT, 
	cover_image VARCHAR(500), 
	location VARCHAR(200), 
	start_date TIMESTAMP WITH TIME ZONE NOT NULL, 
	end_date TIMESTAMP WITH TIME ZONE, 
	is_virtual BOOLEAN NOT NULL, 
	registration_url VARCHAR(500), 
	is_published BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug), 
	UNIQUE (slug)
);


CREATE TABLE faqs (
	question VARCHAR(500) NOT NULL, 
	answer TEXT NOT NULL, 
	category VARCHAR(100) NOT NULL, 
	"order" INTEGER NOT NULL, 
	is_published BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);


CREATE TABLE industries (
	name VARCHAR(150) NOT NULL, 
	slug VARCHAR(170) NOT NULL, 
	icon VARCHAR(255), 
	description TEXT, 
	cover_image VARCHAR(500), 
	is_published BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (name), 
	UNIQUE (slug), 
	UNIQUE (slug), 
	UNIQUE (name)
);


CREATE TABLE newsletter_subscribers (
	email VARCHAR(255) NOT NULL, 
	name VARCHAR(150), 
	is_active BOOLEAN NOT NULL, 
	subscribed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	unsubscribed_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_newsletter_subscribers_email ON newsletter_subscribers (email);


CREATE TABLE page_contents (
	slug VARCHAR(150) NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	content TEXT, 
	is_published BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_page_contents_slug ON page_contents (slug);


CREATE TABLE page_views (
	path VARCHAR(500) NOT NULL, 
	ip_address VARCHAR(50), 
	user_agent TEXT, 
	referrer VARCHAR(500), 
	country VARCHAR(100), 
	viewed_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_page_views_path ON page_views (path);

CREATE INDEX ix_page_views_viewed_at ON page_views (viewed_at);


CREATE TABLE partners (
	name VARCHAR(200) NOT NULL, 
	logo VARCHAR(500), 
	website VARCHAR(500), 
	type partner_type NOT NULL, 
	is_published BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);


CREATE TABLE permissions (
	name VARCHAR(150) NOT NULL, 
	module VARCHAR(100) NOT NULL, 
	action VARCHAR(50) NOT NULL, 
	description VARCHAR(255), 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (name), 
	UNIQUE (name)
);


CREATE TABLE products (
	name VARCHAR(200) NOT NULL, 
	slug VARCHAR(220) NOT NULL, 
	tagline VARCHAR(300), 
	description TEXT, 
	features VARCHAR[], 
	benefits VARCHAR[], 
	pricing_tiers JSONB, 
	technology_stack VARCHAR[], 
	use_cases VARCHAR[], 
	cover_image VARCHAR(500), 
	icon VARCHAR(255), 
	is_published BOOLEAN NOT NULL, 
	"order" INTEGER NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug), 
	UNIQUE (slug)
);


CREATE TABLE roles (
	name VARCHAR(100) NOT NULL, 
	slug VARCHAR(100) NOT NULL, 
	description TEXT, 
	is_system BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (name), 
	UNIQUE (slug), 
	UNIQUE (name), 
	UNIQUE (slug)
);


CREATE TABLE seo_metadata (
	page_path VARCHAR(255) NOT NULL, 
	title VARCHAR(160), 
	description VARCHAR(320), 
	keywords VARCHAR(500), 
	og_title VARCHAR(160), 
	og_description VARCHAR(320), 
	og_image VARCHAR(500), 
	og_type VARCHAR(50), 
	canonical_url VARCHAR(500), 
	schema_markup JSONB, 
	no_index BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_seo_metadata_page_path ON seo_metadata (page_path);


CREATE TABLE services (
	name VARCHAR(200) NOT NULL, 
	slug VARCHAR(220) NOT NULL, 
	icon VARCHAR(255), 
	overview TEXT, 
	business_problems TEXT, 
	solutions TEXT, 
	features VARCHAR[], 
	benefits VARCHAR[], 
	process JSONB, 
	technology_stack VARCHAR[], 
	deliverables VARCHAR[], 
	related_industries VARCHAR[], 
	cover_image VARCHAR(500), 
	is_published BOOLEAN NOT NULL, 
	"order" INTEGER NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug), 
	UNIQUE (slug)
);


CREATE TABLE settings (
	key VARCHAR(150) NOT NULL, 
	value JSONB, 
	"group" VARCHAR(50) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (key), 
	UNIQUE (key)
);


CREATE TABLE solutions (
	name VARCHAR(200) NOT NULL, 
	slug VARCHAR(220) NOT NULL, 
	icon VARCHAR(255), 
	overview TEXT, 
	problem_statement TEXT, 
	approach VARCHAR[], 
	outcomes VARCHAR[], 
	related_industries VARCHAR[], 
	related_services VARCHAR[], 
	cover_image VARCHAR(500), 
	is_published BOOLEAN NOT NULL, 
	"order" INTEGER NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug), 
	UNIQUE (slug)
);


CREATE TABLE technologies (
	name VARCHAR(150) NOT NULL, 
	category technology_category NOT NULL, 
	logo VARCHAR(500), 
	description TEXT, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (name), 
	UNIQUE (name)
);


CREATE TABLE users (
	id UUID NOT NULL, 
	name VARCHAR(150) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	phone VARCHAR(30), 
	avatar VARCHAR(500), 
	role user_role NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	is_email_verified BOOLEAN NOT NULL, 
	last_login_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_users_email ON users (email);


CREATE TABLE applications (
	career_id UUID NOT NULL, 
	full_name VARCHAR(150) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	phone VARCHAR(30), 
	resume_url VARCHAR(500) NOT NULL, 
	cover_letter TEXT, 
	linkedin_url VARCHAR(500), 
	status application_status NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(career_id) REFERENCES careers (id)
);


CREATE TABLE audit_logs (
	user_id UUID, 
	action VARCHAR(150) NOT NULL, 
	entity_type VARCHAR(100), 
	entity_id UUID, 
	ip_address VARCHAR(50), 
	user_agent VARCHAR(255), 
	log_metadata JSONB, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);


CREATE TABLE blogs (
	title VARCHAR(255) NOT NULL, 
	slug VARCHAR(280) NOT NULL, 
	excerpt VARCHAR(500), 
	content TEXT NOT NULL, 
	cover_image VARCHAR(500), 
	author_id UUID, 
	category_id UUID, 
	tags VARCHAR[], 
	status blog_status NOT NULL, 
	views INTEGER NOT NULL, 
	published_at TIMESTAMP WITH TIME ZONE, 
	meta_title VARCHAR(255), 
	meta_description VARCHAR(500), 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug), 
	UNIQUE (slug), 
	FOREIGN KEY(author_id) REFERENCES users (id), 
	FOREIGN KEY(category_id) REFERENCES categories (id)
);


CREATE TABLE courses (
	title VARCHAR(255) NOT NULL, 
	slug VARCHAR(280) NOT NULL, 
	description TEXT, 
	category VARCHAR(100), 
	duration_hours INTEGER, 
	cover_image VARCHAR(500), 
	is_published BOOLEAN NOT NULL, 
	created_by UUID, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug), 
	UNIQUE (slug), 
	FOREIGN KEY(created_by) REFERENCES users (id)
);


CREATE TABLE employees (
	user_id UUID NOT NULL, 
	employee_code VARCHAR(50) NOT NULL, 
	department_id UUID, 
	designation VARCHAR(150), 
	date_of_joining DATE, 
	date_of_birth DATE, 
	employment_type employment_type NOT NULL, 
	status employee_status NOT NULL, 
	office_location VARCHAR(100), 
	reporting_manager_id UUID, 
	salary NUMERIC(12, 2), 
	address TEXT, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (user_id), 
	UNIQUE (employee_code), 
	UNIQUE (employee_code), 
	UNIQUE (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(department_id) REFERENCES departments (id), 
	FOREIGN KEY(reporting_manager_id) REFERENCES employees (id)
);


CREATE TABLE media (
	file_name VARCHAR(255) NOT NULL, 
	url VARCHAR(500) NOT NULL, 
	mime_type VARCHAR(100), 
	size_bytes INTEGER, 
	uploaded_by UUID, 
	folder VARCHAR(100) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(uploaded_by) REFERENCES users (id)
);


CREATE TABLE notifications (
	user_id UUID NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	message TEXT, 
	type notification_type NOT NULL, 
	link VARCHAR(500), 
	is_read BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);


CREATE TABLE reports (
	title VARCHAR(255) NOT NULL, 
	report_type VARCHAR(100) NOT NULL, 
	period VARCHAR(100) NOT NULL, 
	generated_by UUID, 
	file_url VARCHAR(500), 
	size_bytes INTEGER, 
	summary TEXT, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(generated_by) REFERENCES users (id)
);


CREATE TABLE resources (
	title VARCHAR(255) NOT NULL, 
	slug VARCHAR(280) NOT NULL, 
	resource_type VARCHAR(50) NOT NULL, 
	description TEXT, 
	file_url VARCHAR(500), 
	cover_image VARCHAR(500), 
	author_id UUID, 
	download_count INTEGER NOT NULL, 
	is_published BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug), 
	UNIQUE (slug), 
	FOREIGN KEY(author_id) REFERENCES users (id)
);


CREATE TABLE role_permissions (
	role_id UUID NOT NULL, 
	permission_id UUID NOT NULL, 
	PRIMARY KEY (role_id, permission_id), 
	FOREIGN KEY(role_id) REFERENCES roles (id), 
	FOREIGN KEY(permission_id) REFERENCES permissions (id)
);


CREATE TABLE attendance (
	employee_id UUID NOT NULL, 
	date DATE NOT NULL, 
	check_in TIME WITHOUT TIME ZONE, 
	check_out TIME WITHOUT TIME ZONE, 
	status attendance_status NOT NULL, 
	notes VARCHAR(255), 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_attendance_employee_date UNIQUE (employee_id, date), 
	FOREIGN KEY(employee_id) REFERENCES employees (id)
);


CREATE TABLE clients (
	user_id UUID NOT NULL, 
	company_name VARCHAR(200), 
	industry VARCHAR(100), 
	country VARCHAR(100), 
	website VARCHAR(255), 
	billing_address TEXT, 
	account_manager_id UUID, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (user_id), 
	UNIQUE (user_id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(account_manager_id) REFERENCES employees (id)
);


CREATE TABLE comments (
	blog_id UUID NOT NULL, 
	name VARCHAR(150) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	content TEXT NOT NULL, 
	status comment_status NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(blog_id) REFERENCES blogs (id)
);


CREATE TABLE employee_documents (
	employee_id UUID NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	type document_type NOT NULL, 
	file_url VARCHAR(500) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(employee_id) REFERENCES employees (id)
);


CREATE TABLE leaves (
	employee_id UUID NOT NULL, 
	type leave_type NOT NULL, 
	start_date DATE NOT NULL, 
	end_date DATE NOT NULL, 
	reason TEXT, 
	status leave_status NOT NULL, 
	approved_by UUID, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(employee_id) REFERENCES employees (id), 
	FOREIGN KEY(approved_by) REFERENCES users (id)
);


CREATE TABLE payslips (
	employee_id UUID NOT NULL, 
	month INTEGER NOT NULL, 
	year INTEGER NOT NULL, 
	basic NUMERIC(12, 2) NOT NULL, 
	allowances NUMERIC(12, 2) NOT NULL, 
	deductions NUMERIC(12, 2) NOT NULL, 
	net_pay NUMERIC(12, 2) NOT NULL, 
	file_url VARCHAR(500), 
	status payslip_status NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_payslip_employee_period UNIQUE (employee_id, month, year), 
	FOREIGN KEY(employee_id) REFERENCES employees (id)
);


CREATE TABLE performance_reviews (
	employee_id UUID NOT NULL, 
	reviewer_id UUID NOT NULL, 
	review_period VARCHAR(50) NOT NULL, 
	review_date DATE NOT NULL, 
	rating INTEGER, 
	strengths TEXT, 
	areas_for_improvement TEXT, 
	goals TEXT, 
	comments TEXT, 
	status VARCHAR(20) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(employee_id) REFERENCES employees (id), 
	FOREIGN KEY(reviewer_id) REFERENCES users (id)
);


CREATE TABLE training_enrollments (
	employee_id UUID NOT NULL, 
	course_id UUID NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	enrolled_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(employee_id) REFERENCES employees (id), 
	FOREIGN KEY(course_id) REFERENCES courses (id)
);


CREATE TABLE client_files (
	client_id UUID NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	category VARCHAR(100) NOT NULL, 
	file_url VARCHAR(500) NOT NULL, 
	size_bytes INTEGER, 
	uploaded_by VARCHAR(150), 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(client_id) REFERENCES clients (id)
);


CREATE TABLE client_reports (
	client_id UUID NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	report_type VARCHAR(100) NOT NULL, 
	period VARCHAR(50) NOT NULL, 
	file_url VARCHAR(500), 
	size_bytes INTEGER, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(client_id) REFERENCES clients (id)
);


CREATE TABLE leads (
	contact_submission_id UUID, 
	company VARCHAR(200), 
	contact_name VARCHAR(150) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	phone VARCHAR(30), 
	source lead_source NOT NULL, 
	status lead_status NOT NULL, 
	estimated_value NUMERIC(12, 2), 
	notes TEXT, 
	owner_id UUID, 
	converted_client_id UUID, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(contact_submission_id) REFERENCES contact_submissions (id), 
	FOREIGN KEY(owner_id) REFERENCES users (id), 
	FOREIGN KEY(converted_client_id) REFERENCES clients (id)
);


CREATE TABLE projects (
	title VARCHAR(200) NOT NULL, 
	slug VARCHAR(220) NOT NULL, 
	client_id UUID, 
	overview TEXT, 
	challenge TEXT, 
	solution TEXT, 
	technology_stack VARCHAR[], 
	architecture_notes TEXT, 
	industry VARCHAR(100), 
	start_date DATE, 
	end_date DATE, 
	budget NUMERIC(14, 2), 
	status project_status NOT NULL, 
	progress_percent INTEGER NOT NULL, 
	project_manager_id UUID, 
	cover_image VARCHAR(500), 
	video_url VARCHAR(500), 
	is_featured BOOLEAN NOT NULL, 
	is_published BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug), 
	UNIQUE (slug), 
	FOREIGN KEY(client_id) REFERENCES clients (id), 
	FOREIGN KEY(project_manager_id) REFERENCES users (id)
);


CREATE TABLE testimonials (
	client_id UUID, 
	author_name VARCHAR(150) NOT NULL, 
	author_title VARCHAR(150), 
	company_name VARCHAR(200), 
	avatar VARCHAR(500), 
	rating INTEGER NOT NULL, 
	content TEXT NOT NULL, 
	is_published BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(client_id) REFERENCES clients (id)
);


CREATE TABLE tickets (
	ticket_number VARCHAR(50) NOT NULL, 
	client_id UUID, 
	subject VARCHAR(255) NOT NULL, 
	description TEXT NOT NULL, 
	priority ticket_priority NOT NULL, 
	status ticket_status NOT NULL, 
	assigned_to UUID, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (ticket_number), 
	UNIQUE (ticket_number), 
	FOREIGN KEY(client_id) REFERENCES clients (id), 
	FOREIGN KEY(assigned_to) REFERENCES users (id)
);


CREATE TABLE case_studies (
	title VARCHAR(255) NOT NULL, 
	slug VARCHAR(280) NOT NULL, 
	project_id UUID, 
	client_name VARCHAR(200), 
	industry VARCHAR(100), 
	problem TEXT, 
	solution TEXT, 
	implementation TEXT, 
	result TEXT, 
	roi VARCHAR(100), 
	customer_feedback TEXT, 
	download_url VARCHAR(500), 
	cover_image VARCHAR(500), 
	is_published BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug), 
	UNIQUE (slug), 
	FOREIGN KEY(project_id) REFERENCES projects (id)
);


CREATE TABLE gallery (
	title VARCHAR(200), 
	image_url VARCHAR(500) NOT NULL, 
	type gallery_type NOT NULL, 
	project_id UUID, 
	album_name VARCHAR(150), 
	is_published BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id)
);


CREATE TABLE invoices (
	invoice_number VARCHAR(50) NOT NULL, 
	client_id UUID NOT NULL, 
	project_id UUID, 
	amount NUMERIC(14, 2) NOT NULL, 
	tax NUMERIC(14, 2) NOT NULL, 
	total_amount NUMERIC(14, 2) NOT NULL, 
	currency VARCHAR(10) NOT NULL, 
	issue_date DATE NOT NULL, 
	due_date DATE NOT NULL, 
	status invoice_status NOT NULL, 
	notes TEXT, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (invoice_number), 
	UNIQUE (invoice_number), 
	FOREIGN KEY(client_id) REFERENCES clients (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id)
);


CREATE TABLE meetings (
	project_id UUID, 
	client_id UUID, 
	title VARCHAR(255) NOT NULL, 
	agenda TEXT, 
	scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	duration_minutes INTEGER NOT NULL, 
	meeting_link VARCHAR(500), 
	organizer_id UUID, 
	status meeting_status NOT NULL, 
	notes TEXT, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(client_id) REFERENCES clients (id), 
	FOREIGN KEY(organizer_id) REFERENCES users (id)
);


CREATE TABLE portfolios (
	title VARCHAR(200) NOT NULL, 
	slug VARCHAR(220) NOT NULL, 
	category VARCHAR(100), 
	thumbnail VARCHAR(500), 
	description TEXT, 
	live_url VARCHAR(500), 
	project_id UUID, 
	is_featured BOOLEAN NOT NULL, 
	"order" INTEGER NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (slug), 
	UNIQUE (slug), 
	FOREIGN KEY(project_id) REFERENCES projects (id)
);


CREATE TABLE project_members (
	project_id UUID NOT NULL, 
	employee_id UUID NOT NULL, 
	PRIMARY KEY (project_id, employee_id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(employee_id) REFERENCES employees (id)
);


CREATE TABLE proposals (
	lead_id UUID NOT NULL, 
	version INTEGER NOT NULL, 
	scope_summary TEXT NOT NULL, 
	price NUMERIC(12, 2) NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	status proposal_status NOT NULL, 
	file_url VARCHAR(500), 
	sent_at TIMESTAMP WITH TIME ZONE, 
	viewed_at TIMESTAMP WITH TIME ZONE, 
	created_by UUID, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(lead_id) REFERENCES leads (id), 
	FOREIGN KEY(created_by) REFERENCES users (id)
);


CREATE TABLE tasks (
	project_id UUID NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	description TEXT, 
	assigned_to UUID, 
	priority task_priority NOT NULL, 
	status task_status NOT NULL, 
	due_date DATE, 
	estimated_hours NUMERIC(6, 2), 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(assigned_to) REFERENCES users (id)
);


CREATE TABLE ticket_replies (
	ticket_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	message TEXT NOT NULL, 
	attachment_url VARCHAR(500), 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(ticket_id) REFERENCES tickets (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);


CREATE TABLE contracts (
	proposal_id UUID NOT NULL, 
	document_url VARCHAR(500), 
	status contract_status NOT NULL, 
	signed_by_client_at TIMESTAMP WITH TIME ZONE, 
	signed_by_company_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	UNIQUE (proposal_id), 
	UNIQUE (proposal_id), 
	FOREIGN KEY(proposal_id) REFERENCES proposals (id)
);


CREATE TABLE payments (
	invoice_id UUID NOT NULL, 
	amount NUMERIC(14, 2) NOT NULL, 
	method payment_method NOT NULL, 
	transaction_ref VARCHAR(150), 
	paid_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	status payment_status NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(invoice_id) REFERENCES invoices (id)
);


CREATE TABLE timesheets (
	employee_id UUID NOT NULL, 
	project_id UUID, 
	task_id UUID, 
	date DATE NOT NULL, 
	hours NUMERIC(4, 2) NOT NULL, 
	description TEXT, 
	status timesheet_status NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	deleted_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(employee_id) REFERENCES employees (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id), 
	FOREIGN KEY(task_id) REFERENCES tasks (id)
);
